name: trimesh-dask-cookbook 
channels:
  - conda-forge
dependencies:
  - xarray
  - numpy
  - pandas
  - fsspec
  - configparser
  - dask-gateway
  - geoviews
  - hvplot
  - jupyter-book
  - jupyterlab
  - pip
  - pip:
      - sphinx-pythia-theme
